#!/bin/bash -l

# Run a job on 1 core + 1 GPU
# login to deneb1 or deneb2 to submit

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --time=48:00:00

source /home/maydin/SemesterProject/venv/bin/activate

python3 ./train.py  --T_p 1 --T_h 7 --data "ewz_daily" --epoch 100 --is_test False --graph_method 'learnable' --gc_type 'vanilla' --temporal_type "conv" --k 16
