#!/bin/bash -l

# Run a job on 1 core + 1 GPU
# login to deneb1 or deneb2 to submit

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --time=48:00:00

source /home/maydin/SemesterProject/venv/bin/activate

DATA='electricity_benchmark'
GRAPH_METHOD='fixed'
GC_TYPE='vanilla'
TEMPORAL_TYPE='lstm'
K=0

python3 ./train.py \
  --T_p 1 \
  --T_h 24 \
  --data "$DATA" \
  --epoch 100 \
  --is_test False \
  --graph_method "$GRAPH_METHOD" \
  --gc_type "$GC_TYPE" \
  --temporal_type "$TEMPORAL_TYPE" \
  --k "$K"


python3 ./pred.py \
  --data "$DATA" \
  --graph_method "$GRAPH_METHOD" \
  --gc_type "$GC_TYPE" \
  --temporal_type "$TEMPORAL_TYPE" \
  --k "$K"
